#!/usr/bin/env bash
#Install nginx web server
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www
bash -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
