#!/usr/bin/env bash
#Install nginx web server
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sed -i '24i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
