#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo dd of=/var/www/html/index.nginx-debian.html

nginx_conf="/etc/nginx/nginx.conf"
custom_header="add_header X-Server-By $(hostname);"

while IFS= read -r line; do
    if [[ $line =~ server[[:space:]]*\{ ]]; then
        echo "$line" >> "$nginx_conf"
	echo "    $custom_header" >> "$nginx_conf"
    fi
done

sudo service nginx restart
