#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

nginx_conf="/etc/nginx/nginx.conf"
custom_header="add_header X-Server-By $(hostname);"

while IFS= read -r line; do
    if [[ $line =~ server[[:space:]]*\{ ]]; then
        echo "$line" >> "$nginx_conf"
	echo "    $custom_header" >> "$nginx_conf"
    fi
done
