#!/usr/bin/env bash
#this script prints 'Best School' apart from the 4th and 8th iteration
i=1
while (( i < 11 )); do
	if (( i == 4 )); then
		echo "bad luck"
	elif (( i == 8 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
